version: '3'

services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <DB_PASSWORD>
    ports:
      - "5432:5432"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:5001"